### ISSUE TITLE
Include openwrt snapshot key

### ISSUE THREAD

**Issue by kevinmehall** [tessel/openwrt-tessel#12]
`opkg update`  fails with

```
Downloading http://downloads.openwrt.org/snapshots/trunk/ramips/mt7620/packages/base/Packages.gz.
Updated list of available packages in /var/opkg-lists/chaos_calmer_base.
Downloading http://downloads.openwrt.org/snapshots/trunk/ramips/mt7620/packages/base/Packages.sig.
Signature check failed.
Remove wrong Signature file.
```

Current workaround is to put 

```
untrusted comment: openwrt.org snapshot build key
RWSvIveoiFjI6WS/h3J8Us0wUEjA53cQLuHJEwOD/sT5JsGvguZjlKmU
```

in  `/etc/opkg/keys/af22f7a88858c8e9`

Is there a better way to do this than to put it in the `files` directory of this repo?

**Comment by jiahuang** [comment]
I just tried another opkg update on the 04's and I'm now getting a different failure mode in that `http://downloads.openwrt.org/snapshots/trunk/ramips/mt7620/packages/base/Packages.gz` 404s

**Comment by kevinmehall** [comment]
It looks like the `.gz` one is no longer there. It's called `Packages` and is uncompressed. You may be able to change `src/gz` to `src` in `/etc/opkg.conf`, and presumably when we rebase on openwrt, that will be the default.

**Comment by kevinmehall** [comment]
Fixed upstream
