### ISSUE TITLE
SPI daemon can freeze OpenWRT (or at least the serial console)

### ISSUE THREAD

**Issue by johnnyman727** [tessel/openwrt-tessel#21]
If I power up T2, then immediately run t2 list (which requests the hostname from OpenWRT) before OpenWRT is fully booted (the console is visible), I can no longer control OpenWRT over the serial console.

**Comment by kevinmehall** [comment]
I'd suspect a samd21 crash given those symptoms, rather than the openwrt system completely freezing. Try it with SWD attached.

**Comment by flaki** [comment]
Wow this just happened to me this morning, didn't know what was up, as my T2 stopped responding. Only a restart breathed new life into the console.

**Comment by johnnyman727** [comment]
We've confirmed that this is an issue with the CLI. You can follow along here: https://github.com/tessel/t2-cli/issues/346
