### ISSUE TITLE
Set hostname and wireless info on first boot

### ISSUE THREAD

**Issue by johnnyman727** [tessel/openwrt-tessel#3]
The hostname of the Tessel should be set to the serial number of the SAMD21 upon first boot. In addition, we'll want to set our own network and wireless files within `/etc/config/network` and `/etc.config/wireless`.

**Comment by johnnyman727** [comment]
This is partially fixed by setting the hostname to `Tessel-MACADDR`. We still need to set the default network and wireless configuration.

**Comment by johnnyman727** [comment]
Temporary workaround - get shell access on the device, then modify /etc/config/wireless with
```
config wifi-device  radio0
    option type 	mac80211
    option channel  11
    option hwmode    11g
    option path    '10180000.wmac'
    option htmode    HT20

config wifi-iface
    option device   radio0
    option network  lan
    option mode 	sta
    option ssid 	{THE SSID YOU WANT TO USE}
    option encryption psk2
    option key { THE PASSWORD FOR THE NETWORK }

```

Then edit /etc/config/network with:
```
config interface 'loopback'
    option ifname 'lo'
    option proto 'static'
    option ipaddr '127.0.0.1'
    option netmask '255.0.0.0'

config globals 'globals'
    option ula_prefix 'fd87:e99f:34ad::/48'

config interface 'lan'
    option ifname 'wlan0'
    option proto 'dhcp'

config switch 'mt7620'
	option enable_vlan 0
```

Then run the following shell command:
```
/etc/init.d/network restart
```

**Comment by johnnyman727** [comment]
Will be fixed when https://github.com/tessel/openwrt-tessel/pull/14 lands.

**Comment by kevinmehall** [comment]
Landed
