### ISSUE TITLE
Connecting to wifi broken for new builds

### ISSUE THREAD

**Issue by johnnyman727** [tessel/openwrt-tessel#43]
Will be fixed by #41.

Smoke Test: Use the [python flashing tools](https://github.com/tessel/t2-firmware/pull/143/) to overwrite a Tessel with the latest OpenWRT build. We have to use the python tool because it actually erases memory whereas `sysupgrade` preserves some files like wireless configuration. Then run `t2 wifi -n SSID -p PASS` from the CLI. Because the `ap` is enabled by default and doesn't have all the required fields, wireless configuration is broken

**Comment by kevinmehall** [comment]
FYI: the `firstboot` command will reset to the openwrt configuration in squashfs, throwing out everything in the overlay.

`sysupgrade` also has a `-n` option that doesn't preserve settings from the overlay.
https://wiki.openwrt.org/doc/techref/sysupgrade

**Comment by johnnyman727** [comment]
That's really useful to know for when we test these new builds. Thanks @kevinmehall!
