### ISSUE TITLE
opkg kernel modules fail to install

### ISSUE THREAD

**Issue by vsviridov** [tessel/openwrt-tessel#56]
They seem to require `kernel-3.18.14` but tessel runs on `kernel-3.18.17`.

**Comment by johnnyman727** [comment]
@kevinmehall mentioned that this might be fixed when we update OpenWRT. I plan on rebasing it sometime this week so we can circle back after I do that.

**Comment by k45514n** [comment]
Closing -- issue is fixed, tested on Tessel 2
