### ISSUE TITLE
Node 8 Build Testing

### ISSUE THREAD

**Issue by rwaldron** [tessel/openwrt-tessel#77]
Here's how I confirmed this build:

1. Connect a Tessel 2 to your local machine. **Make sure it has a WiFi connection!!**
2. Create a temporary working directory, download the builds and update the Tessel 2: 
    ```
    tmp=$(mktemp -d -t "tessel-release.XXXXXXXX");
    mkdir $tmp/builds;
    cd $tmp;
    wget https://www.dropbox.com/s/cijlesmhfflkj0i/d81c023d18e85bc3ea36b379c7dbb46d12c256ae.tar.gz?dl=0 -O builds.tar.gz;
    tar -zxvf $tmp/builds.tar.gz -C $tmp/builds/;
    t2 update --openwrt-path=$tmp/builds/openwrt.bin --firmware-path=$tmp/builds/firmware.bin;
    ```
3. SSH to Tessel 2 (requires WiFi)
    ```
    t2 root
    ```
4. Once on board, verify the Node version: 
    ```
    node -v
    ```
5. Exit the connection: 
    ```
    exit;
    ```

At this point I would HIGHLY recommend testing the installation with some projects that are pure JS, as we do not yet have support for pre-compiled modules. I've file an issue for that.

**Comment by HipsterBrown** [comment]
Can’t wait to test this out. 👏

**Comment by HipsterBrown** [comment]
This worked for me. Tested out a basic program:

```es6
const { promisify } = require('util');
const tessel = require('tessel');

const green = tessel.led[2];
const toggle = promisify(green.toggle).bind(green);

const sleep = (wait = 1000) => new Promise((resolve) => setTimeout(resolve, wait));

const main = async () => {
  while (true) {
    console.log('Toggling the green led');
    await toggle();

    console.log('Sleeping for 2 seconds');
    await sleep(2000);
  }
};

main().catch(console.error);
```

**Comment by rwaldron** [comment]
ooooo that's sassy

**Comment by k45514n** [comment]
Do we need more testers? Happy to help and I have a couple Tessels I can use. Otherwise, do we close this?

**Comment by k45514n** [comment]
Closing as Node 8 is running on Tessel 2
